### ISSUE TITLE
Corrupted PDFs

### ISSUE THREAD

**Issue by mikemand** [danielwestendorf/breezy-pdf-lite#12]
Hello, after getting Breezy set up on my server (CentOS 7 from https://webfaction.com), I was able to successfully run the command from the readme:

```sh
$ curl -X POST -H 'Authorization: Bearer {myTokenHere}' \
> http://localhost:5001/render/html \
> -d "`curl https://raw.githubusercontent.com/danielwestendorf/breezy-pdf-lite/master/sample.html`" \
> -o example.pdf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 33192  100 33192    0     0  42859      0 --:--:-- --:--:-- --:--:-- 42883
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 33272  100    81  100 33191    921   368k --:--:-- --:--:-- --:--:--  368k
```

After downloading the file from my server to open, it looks like the PDF is corrupt.

<img width="532" alt="screen shot 2018-07-27 at 12 44 08 pm" src="https://user-images.githubusercontent.com/745184/43340844-dc99a3b6-919a-11e8-9499-c1478e852c1f.png">
<img width="532" alt="screen shot 2018-07-27 at 12 44 13 pm" src="https://user-images.githubusercontent.com/745184/43340845-dcb3e9ec-919a-11e8-92f2-79efb06c6ebc.png">

**Comment by mikemand** [comment]
The logs are empty, it looks like:

```sh
$ pm2 logs breezy-pdf --lines 1000
[TAILING] Tailing last 1000 lines for [breezy-pdf] process (change the value with --lines option)
~/.pm2/logs/breezy-pdf-error.log last 1000 lines:
~/.pm2/logs/breezy-pdf-out.log last 1000 lines:
0|breezy-p | Starting web server...
0|breezy-p | Listening for requests at http://localhost:5001...
0|breezy-p | Starting web server...
0|breezy-p | Listening for requests at http://localhost:5001...
```

**Comment by danielwestendorf** [comment]
Can you run with the `DEBUG` ENV variable set? `DEBUG=breezy-pdf-lite:*`.

I assume you have the latest version of Google Chrome installed, and that tests pass?

I'd love to help beyond this, but I can't support deployment issues due to lack of time. If you continue to have problems, I suggest you give the Heroku deployment a shot, they have a free plan.

**Comment by mikemand** [comment]
Hi Daniel,

I'm guessing it was because Google Chrome wasn't installed on my server. Unfortunately, since I don't have root access, I cannot install it myself.

I went ahead and did Heroku, and after fiddling with it I was able to get a valid PDF. For some reason, when the `PRIVATE_TOKEN` was set, the dyno didn't catch it. A restart was required.

Thank you!
