### ISSUE TITLE
header and footer templates not working

### ISSUE THREAD

**Issue by fran-worley** [danielwestendorf/breezy-pdf-lite#47]
Hi, I'm having an issue with the header and footer print options:

- the footer templates seems to be rendering as the header and vice versa.
- the footer wont display page numbers and the header can't display anything!

My template tags:

```html
<meta name="breezy-pdf-headerTemplate" content="<div class='header'><table><tr><td class='date'></td><td><span class='title'></span></td><td><span class='pageNumber'></span>/<span class='totalPages'></span></td></tr></table></div>">

<meta name="breezy-pdf-footerTemplate" content="<div class='footer'><table><tr><td class='date'></td><td><span class='title'></span></td><td><span class='pageNumber'></span>/<span class='totalPages'></span></td></tr></table></div>">
```

Any ideas - I thought I'd followed the docs [here](https://docs.breezypdf.com/metadata#header-and-footer-templates)...

**Comment by danielwestendorf** [comment]
Hey @fran-worley. A few ideas:

- headers and footers won't inherit any page styling
- margins need to accommodate the space for your header and footer. The default 0.4 might not be enough space.

You can see some sample HTML here https://github.com/danielwestendorf/breezy-pdf-lite/blob/master/sample.html

Good luck!
