### ISSUE TITLE
PHP client

### ISSUE THREAD

**Issue by danielwestendorf** [danielwestendorf/breezy-pdf-lite#9]
Vote!

**Comment by jitendra-1217** [comment]
Wip wrapper/client: https://github.com/jitendra-1217/breezy-pdf-lite-php

Please suggest if there is any guideline/suggest approach for clients.

I have referred through the ruby client but this one(php) is pretty simple, haven't included the middleware stuff(probably not needed at the moment, may think later) and will be framework specific.

**Comment by jitendra-1217** [comment]
Thanks for quick review @danielwestendorf . Yes, will update readme with options stuff. 👍
